- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- name: /config/voicechat/voicechat-server.properties
  ansible.builtin.include_tasks: relay.yml
  loop: "{{ instances|zip(instances_secrets) }}"
  loop_control:
    loop_var: instance
    index_var: loop0
  when: 'instance.0.relay_bot.enabled'
