---
- name: Setup
  ansible.builtin.include_tasks: setup.yml

- name: Create Relay bot holding dir
  ansible.builtin.file:
    path: ~/relay
    state: directory
    mode: 0755

- name: Create Relay bot (if enabled)
  ansible.builtin.include_tasks: relay.yml
  loop: "{{ targets.instances }}"
  loop_control:
    loop_var: instance
  when: '"relay_bot" in instance'
