- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Create Relay bot (if enabled)
  ansible.builtin.include_tasks: relay.yml
  loop: "{{ instances|zip(instances_secrets) }}"
  loop_control:
    loop_var: instance
    index_var: loop0
  when: '"relay_bot" in instance.0'
