---
- name: Delete old build data
  ansible.builtin.file:
    state: absent
    path: ~/relay/{{ instance.name }}

- name: Create build directory
  ansible.builtin.file:
    path: ~/relay/{{ instance.name }}
    state: directory
    mode: 0755

- name: Copy files
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/relay/{{ instance.name }}
    recursive: true

- name: Copy instance .mrpack
  ansible.posix.synchronize:
    src: "{{ role_path }}/../../mrpacks/{{ inventory_hostname }}-{{ instance.name }}-{{ lookup('file', role_path + '/../../mrpacks/' + inventory_hostname + '-' + instance.name + '.hash') }}.mrpack"
    dest: ~/relay/{{ instance.name }}/{{ inventory_hostname }}-{{ instance.name }}-{{ lookup('file', role_path + '/../../mrpacks/' + inventory_hostname + '-' + instance.name + '.hash') }}.mrpack
    recursive: true

- name: Generate config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: ~/relay/{{ instance.name }}/config.yml
    mode: 0755

- name: Link log directory
  ansible.builtin.file:
    src: /home/fmcs/{{ instance.name }}/logs
    path: /home/fmcs/relay/{{ instance.name }}/logs
    state: link
    force: yes
    mode: 0755

- name: Template systemd service
  ansible.builtin.template:
    src: service.j2
    dest: ~/.config/systemd/user/mcr-{{ instance.name }}.service
    mode: 0755

- name: Start relay bot
  systemd_service:
    scope: user
    name: mcr-{{ instance.name }}
    enabled: true
    state: restarted
