---
- name: Delete old build data
  ansible.builtin.file:
    state: absent
    path: ~/relay/{{ instance.0.name }}

- name: Create build directory
  ansible.builtin.file:
    path: ~/relay/{{ instance.0.name }}
    state: directory
    mode: 0755

- name: Copy files
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/relay/{{ instance.0.name }}
    recursive: true

- name: Copy instance .mrpack
  ansible.posix.synchronize:
    src: "{{ role_path }}/../../mrpacks/{{ inventory_hostname }}-{{ instance.0.name }}.mrpack"
    dest: ~/relay/{{ instance.0.name }}/{{ inventory_hostname }}-{{ instance.0.name }}.mrpack
    recursive: true

- name: Generate config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: ~/relay/{{ instance.0.name }}/config.yml
    mode: 0755

- name: Link log directory
  ansible.builtin.file:
    src: /home/fmcs/{{ instance.0.name }}/logs
    path: /home/fmcs/relay/{{ instance.0.name }}/logs
    state: link
    mode: 0755

- name: Template systemd service
  ansible.builtin.template:
    src: service.j2
    dest: ~/.config/systemd/user/mcr-{{ instance.0.name }}.service
    mode: 0755

- name: Start relay bot
  systemd_service:
    scope: user
    name: mcr-{{ instance.0.name }}
    enabled: true
    state: restarted
