FROM amazoncorretto:20

WORKDIR /fmcs
# Install Fabric Server
RUN curl -L -o fabric-server-mc.{{ item.minecraft_ver }}-loader.{{ item.fabric_ver }}-launcher.{{ item.fabric_inst_ver }}.jar https://meta.fabricmc.net/v2/versions/loader/{{ item.minecraft_ver }}/{{ item.fabric_ver }}/{{ item.fabric_inst_ver }}/server/jar

WORKDIR /fmcs/mods
# Install Mods
{% for name, mod in item.mods.items() %}
{% if mod.mode != "client" %}
RUN curl -L -o "{{ name }}.jar" {{ mod.source }}
{% endif %}
{% endfor %}

# Copy in generated items
WORKDIR /fmcs
COPY . .

ENTRYPOINT [ "./run.sh" ]
