FROM amazoncorretto:20

WORKDIR /fmcs
# Install Forge Server
RUN curl --output forge-{{ minecraft_ver }}-{{ forge_ver }}-installer.jar https://maven.minecraftforge.net/net/minecraftforge/forge/{{ minecraft_ver }}-{{ forge_ver }}/forge-{{ minecraft_ver }}-{{ forge_ver }}-installer.jar
RUN java -jar forge-{{ minecraft_ver }}-{{ forge_ver }}-installer.jar --installServer
RUN rm forge-{{ minecraft_ver }}-{{ forge_ver }}-installer.jar

WORKDIR /fmcs/mods
# Install Mods
{% for mod in item.mods %}
RUN curl --output "{{ mod.name }}.jar" -L https://www.curseforge.com/api/v1/mods/{{ mod.project }}/files/{{ mod.file }}/download
{% endfor %}

WORKDIR /fmcs
COPY . .
ENTRYPOINT [ "/bin/bash", "./run.sh" ]
