FROM amazoncorretto:20

WORKDIR /server
# Install Server
{% if 'fabric' in item %}
# Fabric
RUN curl -L -o fabric-server-mc.{{ item.minecraft_ver }}-loader.{{ item.fabric }}-launcher.{{ fabric_installer_version }}.jar https://meta.fabricmc.net/v2/versions/loader/{{ item.minecraft_ver }}/{{ item.fabric }}/{{ fabric_installer_version }}/server/jar
{% elif 'forge' in item %}
# Forge
RUN curl -L -o forge-{{ item.minecraft_ver }}-{{ item.forge }}-installer.jar https://maven.minecraftforge.net/net/minecraftforge/forge/{{ item.minecraft_ver }}-{{ item.forge }}/forge-{{ item.minecraft_ver }}-{{ item.forge }}-installer.jar
RUN java -jar forge-{{ item.minecraft_ver }}-{{ item.forge }}-installer.jar --installServer
RUN rm forge-{{ item.minecraft_ver }}-{{ item.forge }}-installer.jar
{% else %}
# Vanilla
# TODO: support this?? raise an error to stop in the meantime
{{ 0/0 }}
{% endif %}

COPY . .
ENTRYPOINT [ "./run.sh" ]
