---
- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Warn update
  ignore_errors: true
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "say Update triggered, restart soon..."
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost

- name: Delete old build data
  ansible.builtin.file:
    state: absent
    path: ~/build/{{ item.name }}
  loop: "{{ instances }}"

- name: Create build directory
  ansible.builtin.file:
    path: ~/build/{{ item.name }}
    state: directory
    mode: 0755
  loop: "{{ instances }}"

# - name: Copy files
#   ansible.posix.synchronize:
#     src: "{{ role_path }}/files/"
#     dest: ~/build/{{ item.name }}
#     recursive: true
#   loop: "{{ instances }}"

##
# Basic config

- name: Accept EULA
  shell: echo eula=true > ~/build/{{ item.name }}/eula.txt
  loop: "{{ instances }}"

- name: Generate whitelist.json
  copy:
    dest: ~/build/{{ item.name }}/whitelist.json
    content: "{{ item.whitelist | to_json }}"
  loop: "{{ instances_secrets }}"

- name: Generate ops.json
  copy:
    dest: ~/build/{{ item.name }}/ops.json
    content: "{{ item.operators | to_json }}"
  loop: "{{ instances_secrets }}"

- name: /server.properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: ~/build/{{ item.0.name }}/server.properties
    mode: 0755
  loop: "{{ instances|zip(instances_secrets) }}"
  loop_control:
    index_var: loop0

- name: /server-icon.png
  ignore_errors: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ inventory_hostname }}/icons/{{ item.name }}.png"
    dest: ~/build/{{ item.name }}/server-icon.png
    mode: 0755
  loop: "{{ instances }}"

- name: /Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: ~/build/{{ item.name }}/Dockerfile
    mode: 0755
  loop: "{{ instances }}"

- name: /run.sh
  ansible.builtin.template:
    src: run.sh.j2
    dest: ~/build/{{ item.name }}/run.sh
    mode: 0755
  loop: "{{ instances }}"

##
# Mod stuff

- name: /config/voicechat
  file:
    path: ~/build/{{ item.name }}/config/voicechat/
    state: directory
  loop: "{{ instances }}"
  loop_control:
    index_var: loop0
  when: '"simple-voice-chat" in item.mods'

- name: /config/voicechat/voicechat-server.properties.properties
  ansible.builtin.template:
    src: voicechat-server.properties.j2
    dest: ~/build/{{ item.name }}/config/voicechat/voicechat-server.properties
    mode: 0755
  loop: "{{ instances }}"
  loop_control:
    index_var: loop0
  when: '"simple-voice-chat" in item.mods'

##
# Build and run

- name: Prune space before building
  community.docker.docker_prune:
    images: true
    containers: true

- name: Build images
  community.docker.docker_image:
    name: "fmcs-{{ item.name }}"
    tag: "latest"
    source: build
    build:
      path: ~/build/{{ item.name }}
      pull: true
    state: present
    force_source: true
    force_tag: true
  loop: "{{ instances }}"

- name: Announce update now!!
  ignore_errors: true
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "say Server is restarting for updates."
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost

- name: Start
  community.docker.docker_container:
    name: "fmcs-{{ item.name }}"
    image: "fmcs-{{ item.name }}:latest"
    state: started
    restart_policy: "unless-stopped"
    volumes:
      - "~/worlds/{{ item.name }}:/fmcs/world"
      - "~/logs/{{ item.name }}:/fmcs/logs"
    ports:
      - "{{ mcs_base_port + (loop0 * 10) }}:{{ mcs_base_port + (loop0 * 10) }}"
      - "{{ mcs_base_port + (loop0 * 10) }}:{{ mcs_base_port + (loop0 * 10) }}/udp"
      - "{{ mcs_base_port + (loop0 * 10) + 1 }}:{{ mcs_base_port + (loop0 * 10) + 1 }}"
      - "{{ mcs_base_port + (loop0 * 10) + 2 }}:{{ mcs_base_port + (loop0 * 10) + 2 }}/udp"
  loop: "{{ instances }}"
  loop_control:
    index_var: loop0

- name: Set up restart cronjob (10AM UTC)
  become: true
  become_method: su
  become_user: root
  ansible.builtin.cron:
    name: "fmcs-restart-{{ item.name }}"
    weekday: "*"
    minute: "0"
    hour: "10"
    job: "docker restart fmcs-{{ item.name }}"
  loop: "{{ instances }}"
  loop_control:
    index_var: loop0
  when: ansible_distribution == 'Ubuntu'