---
- name: Load secrets
  include_tasks: secrets.yml

- name: Generate perms
  include_tasks: gen_perms.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance

- name: Move whitelist.json into container
  community.docker.docker_container_copy_into:
    container: "fmcs-{{ instance.name }}"
    path: ~/build/{{ instance.name }}/whitelist.json
    container_path: /fmcs/whitelist.json
  delegate_to: "{{ inventory_hostname }}"

- name: Move ops.json into container
  community.docker.docker_container_copy_into:
    container: "fmcs-{{ instance.name }}"
    path: ~/build/{{ instance.name }}/ops.json
    container_path: /fmcs/ops.json
  delegate_to: "{{ inventory_hostname }}"

- name: Tell servers to reload whitelist
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "whitelist reload"
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost

- name: Inform whitelist update
  ignore_errors: true
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "say Whitelist updated."
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost
