---
- name: Load secrets
  include_tasks: secrets.yml

- name: Generate perms
  include_tasks: gen_perms.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance

- name: Move whitelist.json into container
  community.docker.docker_container_copy_into:
    container: "mcs-{{ item.name }}"
    path: ~/build/{{ item.name }}/whitelist.json
    container_path: /server/whitelist.json
  loop: "{{ instances }}"
  delegate_to: "{{ ansible_host }}"

- name: Move ops.json into container
  community.docker.docker_container_copy_into:
    container: "mcs-{{ item.name }}"
    path: ~/build/{{ item.name }}/ops.json
    container_path: /server/ops.json
  loop: "{{ instances }}"
  delegate_to: "{{ ansible_host }}"

- name: Tell servers to reload whitelist
  rcon:
    address: "{{ ansible_host }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "whitelist reload"
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost

- name: Inform whitelist update
  ignore_errors: true
  rcon:
    address: "{{ ansible_host }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "say Whitelist updated."
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost
