---
- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- include_tasks: server.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance

- name: Tell servers to reload whitelist
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "whitelist reload"
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost

- name: Inform whitelist update
  ignore_errors: true
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ mcs_base_port + (loop0 * 10) + 1 }}"
    password: "{{ item.rcon_pass }}"
    command: "say Whitelist updated."
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost
