---
- name: Set placeholder names
  set_fact:
    whitelist: "{{ whitelist | default([]) + [{ 'name': 'placeholder', 'uuid': item }] }}"
  with_items: "{{ instance.whitelist }}"

- name: Generate whitelist.json
  copy:
    dest: ~/build/{{ instance.name }}/whitelist.json
    content: "{{ whitelist | to_json }}"

- name: Generate ops.json
  copy:
    dest: ~/build/{{ instance.name }}/ops.json
    content: "{{ instance.operators | to_json }}"

- name: Move whitelist.json into container
  community.docker.docker_container_copy_into:
    container: "fmcs-{{ instance.name }}"
    path: ~/build/{{ instance.name }}/whitelist.json
    container_path: /fmcs/whitelist.json
  delegate_to: "{{ inventory_hostname }}"

- name: Move ops.json into container
  community.docker.docker_container_copy_into:
    container: "fmcs-{{ instance.name }}"
    path: ~/build/{{ instance.name }}/ops.json
    container_path: /fmcs/ops.json
  delegate_to: "{{ inventory_hostname }}"
