instances:
  # - name: "fungus"
  #   minecraft_ver: "1.20.1"
  #   forge_ver: "47.1.0"
  #   difficulty: "easy"
  #   is_whitelist: "true"
  #   gamemode: "survival"
  #   maxplayers: 20
  #   motd: "An Ansible-configured Minecraft server"
  #   pvp: "false"
  #   simdist: 10
  #   viewdist: 12
  #   mods:
  #     - name: "balm"
  #       project: 531761
  #       file: 4584620
  #     - name: "waystones"
  #       project: 245755
  #       file: 4584510

  - name: "chili"
    minecraft_ver: "1.20.1"
    fabric_ver: "0.14.21"
    fabric_inst_ver: "0.11.2"
    ram: "3G"
    seed: ""
    difficulty: "hard"
    hardcore: "false"
    is_whitelist: "true"
    gamemode: "survival"
    maxplayers: 20
    motd: "Chiliverse"
    pvp: "true"
    simdist: 10
    viewdist: 16
    mods:
      fabric-api:
        project: 306612
        file: 4622908
      xaeros-minimap:
        project: 263420
        file: 4593188
      xaeros-world-map:
        project: 317780
        file: 4594989
      simple-voice-chat:
        project: 416089
        file: 4645807
      sound-physics-remastered:
        project: 535489
        file: 4584319

  - name: "chili-smp"
    minecraft_ver: "1.20.1"
    fabric_ver: "0.14.21"
    fabric_inst_ver: "0.11.2"
    ram: "3G"
    seed: ""
    difficulty: "hard"
    hardcore: "false"
    is_whitelist: "true"
    gamemode: "survival"
    maxplayers: 20
    motd: "Chiliverse SMP"
    pvp: "true"
    simdist: 10
    viewdist: 16
    mods:
      fabric-api:
        project: 306612
        file: 4622908
      xaeros-minimap:
        project: 263420
        file: 4593188
      xaeros-world-map:
        project: 317780
        file: 4594989
      simple-voice-chat:
        project: 416089
        file: 4645807
      sound-physics-remastered:
        project: 535489
        file: 4584319
