instances:
  # - name: "fungus"
  #   minecraft_ver: "1.20.1"
  #   forge_ver: "47.1.0"
  #   difficulty: "easy"
  #   is_whitelist: "true"
  #   gamemode: "survival"
  #   maxplayers: 20
  #   motd: "An Ansible-configured Minecraft server"
  #   pvp: "false"
  #   simdist: 10
  #   viewdist: 12
  #   mods:
  #     - name: "balm"
  #       project: 531761
  #       file: 4584620
  #     - name: "waystones"
  #       project: 245755
  #       file: 4584510

  - name: "chili"
    minecraft_ver: "1.20.1"
    fabric_ver: "0.14.21"
    fabric_inst_ver: "0.11.2"
    ram: "3G"
    seed: ""
    difficulty: "hard"
    hardcore: "false"
    is_whitelist: "true"
    gamemode: "survival"
    maxplayers: 20
    motd: "Chiliverse"
    pvp: "true"
    simdist: 10
    viewdist: 16
    mods:
      fabric-api: https://www.curseforge.com/api/v1/mods/306612/files/4622908/download
      inventory-sorting: https://www.curseforge.com/api/v1/mods/325471/files/4597704/download
      xaeros-minimap: https://www.curseforge.com/api/v1/mods/263420/files/4593188/download
      xaeros-world-map: https://www.curseforge.com/api/v1/mods/317780/files/4594989/download
      simple-voice-chat: https://www.curseforge.com/api/v1/mods/416089/files/4645807/download
      sound-physics-remastered: https://www.curseforge.com/api/v1/mods/535489/files/4584319/download

  - name: "chili-smp"
    minecraft_ver: "1.20.1"
    fabric_ver: "0.14.21"
    fabric_inst_ver: "0.11.2"
    ram: "3G"
    seed: ""
    difficulty: "hard"
    hardcore: "false"
    is_whitelist: "true"
    gamemode: "survival"
    maxplayers: 20
    motd: "Chiliverse SMP"
    pvp: "true"
    simdist: 10
    viewdist: 16
    mods:
      fabric-api: https://www.curseforge.com/api/v1/mods/306612/files/4622908/download
      inventory-sorting: https://www.curseforge.com/api/v1/mods/325471/files/4597704/download
      xaeros-minimap: https://www.curseforge.com/api/v1/mods/263420/files/4593188/download
      xaeros-world-map: https://www.curseforge.com/api/v1/mods/317780/files/4594989/download
      simple-voice-chat: https://www.curseforge.com/api/v1/mods/416089/files/4645807/download
      sound-physics-remastered: https://www.curseforge.com/api/v1/mods/535489/files/4584319/download
      fabric-language-kotlin: https://www.curseforge.com/api/v1/mods/308769/files/4628045/download
      ledger: https://www.curseforge.com/api/v1/mods/491137/files/4572696/download
      lithium: https://cdn.modrinth.com/data/gvQqBUqZ/versions/ZSNsJrPI/lithium-fabric-mc1.20.1-0.11.2.jar
