---
- name: Generate restart cronjob and install
  hosts: mc
  tasks:
    # I would like for this to be better but attempting to template otherwise fails.
    - name: Add servers to cron
      set_fact:
        cron: |
          /usr/bin/systemctl --user restart {% for item in instances %}
          mcs-{{ item.name }} {% if 'relay_bot' in item %}
          mcr-{{ item.name }} {% endif %}{% endfor %}

    - name: Install cron
      ansible.builtin.cron:
        name: "mcs-restart"
        weekday: "*"
        minute: "0"
        hour: "{{ daily_restart_hour_utc }}"
        job: "{{ cron }}"
      when: ansible_distribution == 'Ubuntu'
