---
- name: Set placeholder names
  set_fact:
    whitelist: "{{ whitelist | default([]) + [{ 'name': 'placeholder', 'uuid': item }] }}"
  with_items: "{{ instance.whitelist }}"
  when: '"whitelist" in instance'

- name: Set placeholder names
  set_fact:
    operators: "{{ operators | default([]) + [{ 'name': 'placeholder', 'uuid': item.uuid, 'level': item.level, 'bypassesPlayerLimit': item.bypassesPlayerLimit }] }}"
  with_items: "{{ instance.operators }}"

- name: Generate whitelist.json
  copy:
    dest: ~/{{ instance.name }}/whitelist.json
    content: "{{ whitelist | to_json }}"
  when: '"whitelist" in instance'

- name: Generate ops.json
  copy:
    dest: ~/{{ instance.name }}/ops.json
    content: "{{ operators | to_json }}"
