---
- name: Get Modrinth links
  modrinth:
    game_version: "{{ instance.minecraft_ver }}"
    loader: "{{ 'fabric' if 'fabric' in instance else 'forge' if 'forge' in instance }}"
    mods: "{{ instance.mods }}"
  register: modrinth

- name: Delete old mods
  ansible.builtin.file:
    path: ~/{{ instance.name }}/mods
    state: absent

- name: Create mods folder
  ansible.builtin.file:
    path: ~/{{ instance.name }}/mods
    state: directory
    mode: 0755

- name: Download mods
  get_url:
    url: "{{ mod.link }}"
    dest: ~/{{ instance.name }}/mods/{{ mod.name }}.jar
  loop: "{{ modrinth.dls }}"
  loop_control:
    loop_var: mod

- name: Download overrides
  get_url:
    url: "{{ instance.mods[mod].source }}"
    dest: ~/{{ instance.name }}/mods/{{ mod }}.jar
  when: 'not instance.mods[mod] == None and "source" in instance.mods[mod]'
  loop: "{{ instance.mods.keys() }}"
  loop_control:
    loop_var: mod
